version: '3.1'
services:
  locust:
    image: oprietop/locust
    restart: on-failure
    depends_on:
      - grafana
    volumes:
      - ./locust:/locust
    command: >
      locust --master
  locust-slave:
    image: oprietop/locust
    restart: on-failure
    depends_on:
      - locust
    volumes:
      - ./locust:/locust
    command: >
      locust --slave --master-host=locust
  influxdb:
    image: influxdb:alpine
    restart: on-failure
    volumes:
      - ./influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    restart: on-failure
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
  nginx:
    image: nginx:alpine
    restart: on-failure
    depends_on:
      - locust
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - 80:80
